#!/usr/bin/python
import boto3
import sys
import botocore
action= sys.argv[1]
bucket= sys.arg[2]
s3_client= boto3.client('s3')

if action == "create-bucket":
 print "creating bucket"
s3_client.create_bucket(bucket=bucket_name)

s3_resource= boto3.resource('s3')
if action == 'delete bucket':
 print "Deleting Bucket"
 bucket= s3_resource(bucket_name)
 for key in bucket.objects.all():
 key.delete()
 bucket.delete()
